name: CI + CD

on:
  pull_request:
    branches: [development, staging, main]
  push:
    branches: [development, staging, main]
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: "1.25.5"

      - name: Verify Dependencies
        run: go mod verify

      - name: Build
        run: go build -v ./...

      - name: Run go vet
        run: go vet ./...

      - name: Install staticcheck
        run: go install honnef.co/go/tools/cmd/staticcheck@latest

      - name: Run staticcheck
        run: staticcheck ./...

      - name: Test
        run: go test -v ./...

  deploy-dev:
    name: Deploy to Development
    needs: [Build]
    if: github.event_name == 'push' && github.ref == 'refs/heads/development'
    runs-on: ubuntu-latest
    environment:
      name: Development
      url: https://finflowapi-development.up.railway.app
    concurrency: deploy-development
    steps:
      - uses: actions/checkout@v5
      - name: Deploy
        run: echo "Deploying to Development..."

  deploy-staging:
    name: Deploy to Staging
    needs: [Build]
    if: github.event_name == 'push' && github.ref == 'refs/heads/staging'
    runs-on: ubuntu-latest
    environment:
      name: Staging
      url: https://finflowapi-staging.up.railway.app
    concurrency: deploy-staging
    steps:
      - uses: actions/checkout@v5
      - name: Deploy
        run: echo "Deploying to Staging..."

  deploy-prod:
    name: Deploy to Production
    needs: [Build, deploy-staging]
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment:
      name: Production
      url: https://finflowapi.up.railway.app
    concurrency: deploy-production
    steps:
      - uses: actions/checkout@v5
      - name: Deploy
        run: echo "Deploying to Production..."
